# Generated by Django 3.2.3 on 2001-01-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecto2', '0002_alter_encomenda_cor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('apelido', models.CharField(max_length=50)),
                ('dataNascimento', models.DateTimeField()),
                ('telefone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('morada', models.CharField(max_length=40)),
                ('codigo_postal', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
                ('cor', models.IntegerField()),
            ],
        ),
    ]
