# Generated by Django 3.2.3 on 2001-01-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecto2', '0003_encomendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugestao', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Encomenda',
        ),
    ]
